/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import edunova.model.Tecaj;
import edunova.utility.Utility;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.type.ListType;

/**
 *
 * @author Admin
 */
public class TecajnaLista extends javax.swing.JFrame {

    /**
     * Creates new form TecajnaLista
     */
    public TecajnaLista() {
        initComponents();
        
        // ovo bi bilo pametnije da id ukontroler ili utility
        String json = Utility.ucitajURL("http://api.hnb.hr/tecajn/v2");
       // System.out.println(json);
        if(json==null){
            return;
        }
        java.lang.reflect.Type tecajType = 
                new TypeToken<ArrayList<Tecaj>>(){}.getType();

        
        
        List<Tecaj> lista = new Gson().fromJson(json,tecajType);
       
        // zavrsio kontroler ili utility
        
        lblTecajnaLista.setText(lista.get(0).getBroj_tecajnice());
        lblDatum.setText(lista.get(0).getDatum_primjene());
        
        DefaultTableModel m = (DefaultTableModel) tblTecajna.getModel();
        
        lista.forEach((t)->{
            String niz[] = {
                t.getDrzava(),
                t.getDrzava_iso(),
                t.getValuta(),
                String.valueOf(t.getJedinica()),
                t.getKupovni_tecaj(),
                t.getSrednji_tecaj(),
                t.getProdajni_tecaj()
            };
            
            m.addRow(niz);
            
        
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTecajna = new javax.swing.JTable();
        lblTecajnaLista = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblTecajna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Država", "ISO", "Valuta", "Jedinica", "Kupovni", "Srednji", "Prodajni"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTecajna);

        lblTecajnaLista.setText("jLabel1");

        lblDatum.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTecajnaLista)
                .addGap(45, 45, 45)
                .addComponent(lblDatum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTecajnaLista)
                    .addComponent(lblDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblTecajnaLista;
    private javax.swing.JTable tblTecajna;
    // End of variables declaration//GEN-END:variables
}
